### PR TITLE
Game Lobby Updated (Minified)

### PR DESCRIPTION
**Pull request by kevinsun-dev**
## Overview

Updated the assets at the top of Game Lobby to better fit the figma design. Updated player connected/ready signal to opacity update. Cleaned up code for game lobby class.

## Changes Made
- Lobby player slot display update (Not connected = Grey box + text; Connected/not ready = Grey box + normal text; Connected/ready = normal box + text)
- Updated game lobby room id border asset (size + sides stretch to screen edge)
- Updated lobby heading with proper size
- Fixed lobby game settings button position 
- Fixed Stardust Spawning Bug

Changes *not* made (#144):
- Updated lobby missing slot text to "Waiting..."
- Removed saira font and updated json files 

## Screenshots

- Lobby (host @ start)

Screen Shot 2021-05-23 at 10 49 34 PM

- Lobby (host @ user join)

Screen Shot 2021-05-23 at 10 53 32 PM

- Lobby (host @ user ready) 

Screen Shot 2021-05-23 at 10 53 42 PM

### CODE REVIEW

**Comment by JackieW001** [comment]
I also put this on Richard's PR, but do we want to change N/A to Waiting? My reasoning to keep N/A (or possibly just have an empty string) is because waiting text makes it seem like there are 4 others trying to connect when there could be fewer players.

**Comment by kevinsun-dev** [comment]
> I also put this on Richard's PR, but do we want to change N/A to Waiting? My reasoning to keep N/A (or possibly just have an empty string) is because waiting text makes it seem like there are 4 others trying to connect when there could be fewer players.

Whoops, fixed the screenshots. I copy/pasted the markdown from #144 and the images carried over. Fixed

**Review by wlong123 — APPROVED** [review]
Are we going with this instead of the pr Richard currently has open?

**Comment by kevinsun-dev** [comment]
> Are we going with this instead of the pr Richard currently has open?

I think so. It's just a subset of the changes, plus some cleanup and bugfixes.

**Review by steiner26 — APPROVED** [review]
🚀

**Pull request merged**
